# Generated by Django 4.2.5 on 2023-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
